// Mapping of file extensions to mode name
export const extToMode = {
  b: 'brainfuck',
  bf: 'brainfuck',
  c: 'x-c',
  h: 'x-chdr',
  cc: 'x-c++src',
  cpp: 'x-c++src',
  cxx: 'x-c++src',
  C: 'x-c++src',
  'c++': 'x-c++src',
  hh: 'x-c++hdr',
  hpp: 'x-c++hdr',
  hxx: 'x-c++hdr',
  'h++': 'x-c++hdr',
  cs: 'x-csharp',
  m: 'x-objectivec',
  mm: 'x-objectivec',
  java: 'x-java',
  class: 'x-java',
  jar: 'x-java',
  ceylon: 'x-ceylon',
  nut: 'x-squirrel',
  kt: 'x-kotlin',
  kts: 'x-kotlin',
  scala: 'x-scala',
  sc: 'x-scala',
  clj: 'x-clojure',
  cljs: 'x-clojure',
  cljc: 'x-clojure',
  edn: 'x-clojure',
  cbl: 'x-cobol',
  cob: 'x-cobol',
  cpy: 'x-cobol',
  coffee: 'x-coffeescript',
  litcoffee: 'x-coffeescript',
  lisp: 'x-common-lisp',
  lsp: 'x-common-lisp',
  l: 'x-common-lisp',
  cl: 'x-common-lisp',
  fasl: 'x-common-lisp',
  cr: 'x-crystal',
  css: 'css',
  scss: 'x-scss',
  less: 'x-less',
  gss: 'x-gss',
  d: 'x-d',
  elm: 'x-elm',
  erl: 'x-erlang',
  hrl: 'x-erlang',
  f: 'x-fortran',
  for: 'x-fortran',
  f90: 'x-fortran',
  f95: 'x-fortran',
  ml: 'x-ocaml',
  mli: 'x-ocaml',
  fs: 'x-fsharp',
  fsi: 'x-fsharp',
  fsx: 'x-fsharp',
  fsscript: 'x-fsharp',
  go: 'x-go',
  groovy: 'x-groovy',
  haml: 'x-haml',
  hbs: 'x-handlebars-template',
  hs: 'x-haskell',
  lhs: 'x-haskell',
  hx: 'x-haxe',
  hxml: 'x-hxml',
  html: 'html',
  js: 'javascript',
  jsx: 'jsx',
  ts: 'typescript',
  tsx: 'typescript-jsx',
  jl: 'x-julia',
  ls: 'x-livescript',
  lua: 'x-lua',
  md: 'x-markdown',
  mo: 'x-modelica',
  pp: 'x-pascal',
  pas: 'x-pascal',
  inc: 'x-pascal',
  pl: 'x-perl',
  pm: 'x-perl',
  t: 'x-perl',
  pod: 'x-perl',
  phtml: 'x-httpd-php',
  php: 'x-php',
  php3: 'x-php',
  php4: 'x-php',
  php5: 'x-php',
  php7: 'x-php',
  phps: 'x-php',
  ps1: 'x-powershell',
  properties: 'x-properties',
  ini: 'x-ini',
  jade: 'x-jade',
  pug: 'x-pug',
  py: 'x-python',
  pyc: 'x-python',
  pyd: 'x-python',
  pyo: 'x-python',
  pyw: 'x-python',
  pyz: 'x-python',
  r: 'x-rsrc',
  R: 'x-rsrc',
  Rdata: 'x-rsrc',
  rds: 'x-rsrc',
  rda: 'x-rsrc',
  rst: 'x-rst',
  rb: 'x-ruby',
  rbw: 'x-ruby',
  rs: 'x-rustsrc',
  rlib: 'x-rustsrc',
  sass: 'x-sass',
  scm: 'x-scheme',
  ss: 'x-scheme',
  sh: 'x-sh',
  soy: 'x-soy',
  styl: 'x-styl',
  sql: 'x-sql',
  swift: 'x-swift',
  tcl: 'x-tcl',
  tbc: 'x-tcl',
  textile: 'x-textile',
  vb: 'x-vb',
  vbs: 'vbscript',
  vbe: 'vbscript',
  wsf: 'vbscript',
  wsc: 'vbscript',
  yaml: 'x-yaml',
  yml: 'x-yaml',
};

export const modes = [
  'brainfuck',
  'x-c',
  'x-chdr',
  'x-c++src',
  'c++',
  'x-c++hdr',
  'h++',
  'x-csharp',
  'x-objectivec',
  'x-java',
  'x-ceylon',
  'x-squirrel',
  'x-kotlin',
  'x-scala',
  'x-clojure',
  'x-cobol',
  'x-coffeescript',
  'x-common-lisp',
  'x-crystal',
  'css',
  'x-scss',
  'x-less',
  'x-gss',
  'x-d',
  'x-elm',
  'x-erlang',
  'x-fortran',
  'x-ocaml',
  'x-fsharp',
  'x-go',
  'x-groovy',
  'x-haml',
  'x-handlebars-template',
  'x-haskell',
  'x-haxe',
  'x-hxml',
  'html',
  'javascript',
  'jsx',
  'typescript',
  'typescript-jsx',
  'x-julia',
  'x-livescript',
  'x-lua',
  'x-markdown',
  'x-modelica',
  'x-pascal',
  'x-perl',
  'x-httpd-php',
  'x-php',
  'x-powershell',
  'x-properties',
  'x-ini',
  'x-jade',
  'x-pug',
  'x-python',
  'x-rsrc',
  'x-rst',
  'x-ruby',
  'x-rustsrc',
  'x-sass',
  'x-scheme',
  'x-sh',
  'x-soy',
  'x-styl',
  'x-sql',
  'x-swift',
  'x-tcl',
  'x-textile',
  'x-vb',
  'vbscript',
  'x-yaml',
];
